import logger from '@server/logger';
import { createHash, randomUUID } from 'crypto';
import fs from 'fs';
import path from 'path';
import sharp from 'sharp';
import {
  generatePosterBuffer,
  type PosterGenerationConfig,
} from './posterGeneration';

const POSTER_STORAGE_DIR = path.join(process.cwd(), 'config', 'posters');
const POSTER_HASHES_FILE = path.join(POSTER_STORAGE_DIR, 'poster-hashes.json');
const ALLOWED_MIME_TYPES = ['image/jpeg', 'image/png', 'image/webp'];
const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB
const POSTER_WIDTH = 500; // Standard poster width
const POSTER_HEIGHT = 750; // Standard poster height (2:3 ratio)

interface PosterHashRegistry {
  [hash: string]: {
    filename?: string; // Only present if we store the file
    originalName?: string;
    uploadedAt: string;
    type: 'plex-poster' | 'generated-poster' | 'auto-generated-poster';
    collectionIdentifier?: string; // For generated/auto-generated posters: config.id or config.id-userId-mediaType for Overseerr users
    isActive: boolean; // Currently used on a collection
    plexUrl?: string; // For tracking Plex source URL
  };
}

/**
 * Calculate SHA-256 hash of a buffer
 */
function calculatePosterHash(buffer: Buffer): string {
  return createHash('sha256').update(buffer).digest('hex');
}

/**
 * Load poster hash registry from disk
 */
function loadPosterHashRegistry(): PosterHashRegistry {
  try {
    if (fs.existsSync(POSTER_HASHES_FILE)) {
      const data = fs.readFileSync(POSTER_HASHES_FILE, 'utf8');
      return JSON.parse(data);
    }
  } catch (error) {
    logger.warn('Failed to load poster hash registry:', error);
  }
  return {};
}

/**
 * Save poster hash registry to disk
 */
function savePosterHashRegistry(registry: PosterHashRegistry): void {
  try {
    fs.writeFileSync(POSTER_HASHES_FILE, JSON.stringify(registry, null, 2));
  } catch (error) {
    logger.error('Failed to save poster hash registry:', error);
  }
}

/**
 * Add poster to hash registry
 */
function addPosterToRegistry(
  hash: string,
  type: 'plex-poster' | 'generated-poster' | 'auto-generated-poster',
  options: {
    filename?: string;
    originalName?: string;
    collectionIdentifier?: string;
    isActive?: boolean;
    plexUrl?: string;
  } = {}
): void {
  const registry = loadPosterHashRegistry();
  registry[hash] = {
    uploadedAt: new Date().toISOString(),
    type,
    isActive: options.isActive ?? true,
    ...(options.filename && { filename: options.filename }),
    ...(options.originalName && { originalName: options.originalName }),
    ...(options.collectionIdentifier && {
      collectionIdentifier: options.collectionIdentifier,
    }),
    ...(options.plexUrl && { plexUrl: options.plexUrl }),
  };
  savePosterHashRegistry(registry);
}

/**
 * Find existing poster by hash
 */
function findPosterByHash(hash: string): string | null {
  const registry = loadPosterHashRegistry();
  const entry = registry[hash];
  if (entry && entry.filename && posterExists(entry.filename)) {
    return entry.filename;
  }
  // Clean up invalid entry if file doesn't exist
  if (entry && entry.filename && !posterExists(entry.filename)) {
    delete registry[hash];
    savePosterHashRegistry(registry);
  }
  return null;
}

/**
 * Remove hash registry entry by filename
 */
function removePosterFromRegistry(filename: string): void {
  const registry = loadPosterHashRegistry();

  // Find the hash entry that matches this filename
  for (const [hash, entry] of Object.entries(registry)) {
    if (entry.filename === filename) {
      delete registry[hash];
      logger.info(`Removed poster hash registry entry: ${filename}`, {
        hash: hash.substring(0, 8),
      });
      break;
    }
  }

  savePosterHashRegistry(registry);
}

/**
 * Check if a poster hash exists in the registry (regardless of file existence)
 */
function posterHashExists(hash: string): boolean {
  const registry = loadPosterHashRegistry();
  return hash in registry;
}

/**
 * Find existing auto-generated posters by collection identifier
 */
function findAutoGeneratedPostersByCollectionId(
  collectionIdentifier: string
): { hash: string; filename?: string }[] {
  const registry = loadPosterHashRegistry();
  const matches: { hash: string; filename?: string }[] = [];

  for (const [hash, entry] of Object.entries(registry)) {
    if (
      entry.type === 'auto-generated-poster' &&
      entry.collectionIdentifier === collectionIdentifier &&
      entry.isActive
    ) {
      matches.push({ hash, filename: entry.filename });
    }
  }

  return matches;
}

/**
 * Mark existing auto-generated posters as no longer active
 */
function markAutoGeneratedPostersAsInactive(
  posters: { hash: string; filename?: string }[]
): void {
  if (posters.length === 0) return;

  const registry = loadPosterHashRegistry();

  for (const poster of posters) {
    if (registry[poster.hash]) {
      registry[poster.hash].isActive = false;
      logger.info(
        `Marked old auto-generated poster as inactive: ${
          poster.filename || poster.hash.substring(0, 8)
        }`
      );
    }
  }

  // Save updated registry
  savePosterHashRegistry(registry);
}

/**
 * Security: Validate filename to prevent path traversal attacks
 */
function isValidFilename(filename: string): boolean {
  // Check for basic requirements
  if (!filename || typeof filename !== 'string') {
    return false;
  }

  // Prevent path traversal attempts
  if (
    filename.includes('..') ||
    filename.includes('/') ||
    filename.includes('\\')
  ) {
    return false;
  }

  // Allow valid poster filenames (UUID + extension or generated patterns)
  const uuidPattern =
    /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\.(jpg|jpeg|png|webp)$/i;
  const generatedPattern = /^generated_[a-z0-9]+\.(jpg|jpeg|png|webp)$/i;
  const tempGeneratedPattern =
    /^temp_generated_[a-z0-9]+\.(jpg|jpeg|png|webp)$/i;

  return (
    uuidPattern.test(filename) ||
    generatedPattern.test(filename) ||
    tempGeneratedPattern.test(filename)
  );
}

/**
 * Initialize poster storage directory
 */
export function initializePosterStorage(): void {
  try {
    if (!fs.existsSync(POSTER_STORAGE_DIR)) {
      fs.mkdirSync(POSTER_STORAGE_DIR, { recursive: true });
      logger.info(`Created poster storage directory: ${POSTER_STORAGE_DIR}`);
    }
  } catch (error) {
    logger.error('Failed to initialize poster storage directory:', error);
    throw error;
  }
}

/**
 * Save uploaded poster file and return the stored filename
 */
export async function savePosterFile(
  fileBuffer: Buffer,
  mimeType: string,
  originalName?: string
): Promise<string> {
  // Validate mime type
  if (!ALLOWED_MIME_TYPES.includes(mimeType)) {
    throw new Error(
      `Invalid file type. Allowed types: ${ALLOWED_MIME_TYPES.join(', ')}`
    );
  }

  // Validate file size
  if (fileBuffer.length > MAX_FILE_SIZE) {
    throw new Error(
      `File size too large. Maximum size: ${MAX_FILE_SIZE / (1024 * 1024)}MB`
    );
  }

  // Calculate hash to check for duplicates
  const fileHash = calculatePosterHash(fileBuffer);
  const existingFilename = findPosterByHash(fileHash);

  if (existingFilename) {
    logger.info(
      `Duplicate poster detected, reusing existing file: ${existingFilename}`,
      {
        hash: fileHash,
        originalName,
      }
    );
    return existingFilename;
  }

  // Generate unique filename with secure extension mapping
  const extensionMap: Record<string, string> = {
    'image/jpeg': 'jpg',
    'image/png': 'png',
    'image/webp': 'webp',
  };

  const fileExtension = extensionMap[mimeType];
  if (!fileExtension) {
    throw new Error('Unsupported file type');
  }

  const filename = `${randomUUID()}.${fileExtension}`;
  const filePath = path.join(POSTER_STORAGE_DIR, filename);

  let image: sharp.Sharp | null = null;
  try {
    // Security: Validate the image buffer with Sharp (this also prevents malicious files)
    image = sharp(fileBuffer);
    const metadata = await image.metadata();

    // Additional security: Verify it's actually an image
    if (
      !metadata.format ||
      !['jpeg', 'png', 'webp'].includes(metadata.format)
    ) {
      throw new Error('Invalid image format detected');
    }

    // Prevent excessively large images that could cause DoS
    if (
      metadata.width &&
      metadata.height &&
      (metadata.width > 5000 || metadata.height > 5000)
    ) {
      throw new Error('Image dimensions too large');
    }

    // Process and optimize the image while preserving format
    let processedBuffer: Buffer;
    if (metadata.format === 'png') {
      processedBuffer = await image
        .resize(POSTER_WIDTH, POSTER_HEIGHT, {
          fit: 'cover',
          position: 'center',
        })
        .png({ quality: 85 })
        .toBuffer();
    } else if (metadata.format === 'webp') {
      processedBuffer = await image
        .resize(POSTER_WIDTH, POSTER_HEIGHT, {
          fit: 'cover',
          position: 'center',
        })
        .webp({ quality: 85 })
        .toBuffer();
    } else {
      // Default to JPEG for jpeg format or fallback
      processedBuffer = await image
        .resize(POSTER_WIDTH, POSTER_HEIGHT, {
          fit: 'cover',
          position: 'center',
        })
        .jpeg({ quality: 85 })
        .toBuffer();
    }

    // Save to disk
    await fs.promises.writeFile(filePath, processedBuffer);

    // Add to hash registry
    addPosterToRegistry(fileHash, 'generated-poster', {
      filename,
      originalName,
    });

    logger.info(
      `Saved poster file: ${filename}${
        originalName ? ` (original: ${originalName})` : ''
      }`,
      {
        hash: fileHash,
      }
    );
    return filename;
  } catch (error) {
    logger.error('Failed to save poster file:', error);
    throw new Error('Failed to process and save poster file');
  } finally {
    // Cleanup: Ensure Sharp instance is properly destroyed to prevent memory leaks
    if (image) {
      try {
        image.destroy();
      } catch (destroyError) {
        logger.warn('Failed to destroy Sharp instance:', destroyError);
      }
    }
  }
}

/**
 * Delete a poster file
 */
export async function deletePosterFile(filename: string): Promise<void> {
  if (!filename) return;

  // Security: Validate filename to prevent path traversal
  if (!isValidFilename(filename)) {
    throw new Error('Invalid filename');
  }

  const filePath = path.join(POSTER_STORAGE_DIR, filename);

  // Security: Ensure the resolved path is within the poster directory
  if (!filePath.startsWith(POSTER_STORAGE_DIR)) {
    throw new Error('Invalid file path');
  }

  try {
    if (fs.existsSync(filePath)) {
      await fs.promises.unlink(filePath);
      logger.info(`Deleted poster file: ${filename}`);

      // Clean up hash registry entry
      removePosterFromRegistry(filename);
    }
  } catch (error) {
    logger.warn(`Failed to delete poster file ${filename}:`, error);
  }
}

/**
 * Get the full path to a poster file
 */
export function getPosterPath(filename: string): string {
  // Security: Validate filename to prevent path traversal
  if (!isValidFilename(filename)) {
    throw new Error('Invalid filename');
  }

  const filePath = path.join(POSTER_STORAGE_DIR, filename);

  // Security: Ensure the resolved path is within the poster directory
  if (!filePath.startsWith(POSTER_STORAGE_DIR)) {
    throw new Error('Invalid file path');
  }

  return filePath;
}

/**
 * Check if a poster file exists
 */
export function posterExists(filename: string): boolean {
  try {
    // Security validation is handled by getPosterPath
    return fs.existsSync(getPosterPath(filename));
  } catch (error) {
    // Invalid filename or path traversal attempt
    return false;
  }
}

/**
 * Get poster URL for serving via HTTP
 */
export function getPosterUrl(filename: string): string {
  return `/api/v1/collections/poster/${filename}`;
}

/**
 * Clean up orphaned poster files (not referenced by any collection config)
 */
export async function cleanupOrphanedPosters(
  referencedPosters: Set<string>
): Promise<number> {
  try {
    const files = await fs.promises.readdir(POSTER_STORAGE_DIR);
    let deletedCount = 0;

    for (const file of files) {
      if (!referencedPosters.has(file)) {
        await deletePosterFile(file);
        deletedCount++;
      }
    }

    if (deletedCount > 0) {
      logger.info(`Cleaned up ${deletedCount} orphaned poster files`);
    }

    return deletedCount;
  } catch (error) {
    logger.error('Failed to cleanup orphaned posters:', error);
    return 0;
  }
}

/**
 * Get all poster filenames currently stored
 */
export async function getAllPosterFiles(): Promise<string[]> {
  try {
    const files = await fs.promises.readdir(POSTER_STORAGE_DIR);
    return files.filter((file) => /\.(jpg|jpeg|png|webp)$/i.test(file));
  } catch (error) {
    logger.error('Failed to list poster files:', error);
    return [];
  }
}

/**
 * Download and save a poster from a URL
 * @param url The URL to download the poster from
 * @param originalName Optional original name for logging
 * @returns The saved filename or null if failed
 */
export async function downloadAndSavePoster(
  url: string,
  originalName?: string
): Promise<string | null> {
  try {
    const axios = await import('axios');

    // Download the image
    const response = await axios.default.get(url, {
      responseType: 'arraybuffer',
      timeout: 30000,
      maxContentLength: MAX_FILE_SIZE,
      headers: {
        'User-Agent': 'Agregarr/1.0.0',
      },
    });

    // Get content type
    const contentType = response.headers['content-type'] || 'image/jpeg';

    // Validate content type
    if (!ALLOWED_MIME_TYPES.includes(contentType)) {
      logger.warn(`Unsupported content type for poster URL: ${contentType}`, {
        url: originalName ? `${originalName} (${url})` : url,
      });
      return null;
    }

    // Convert to buffer
    const buffer = Buffer.from(response.data);

    // Calculate hash to check for duplicates before processing
    const fileHash = calculatePosterHash(buffer);

    // Check if we have a file for this hash
    const existingFilename = findPosterByHash(fileHash);
    if (existingFilename) {
      logger.info(
        `Duplicate poster detected during download, reusing existing file: ${existingFilename}`,
        {
          hash: fileHash.substring(0, 8),
          url: originalName ? `${originalName} (${url})` : url,
        }
      );
      return existingFilename;
    }

    // Check if hash exists but no file (auto-generated poster case)
    if (posterHashExists(fileHash)) {
      throw new Error(
        'This poster has already been processed and is managed by the system.'
      );
    }

    // Save the poster
    const filename = await savePosterFile(buffer, contentType, originalName);

    // Update registry to mark as plex-poster rather than generated-poster
    const registry = loadPosterHashRegistry();
    if (registry[fileHash]) {
      registry[fileHash].type = 'plex-poster';
      registry[fileHash].plexUrl = url;
      savePosterHashRegistry(registry);
    }

    logger.info(`Downloaded and saved poster from URL`, {
      url: originalName ? `${originalName} (${url})` : url,
      filename,
      size: buffer.length,
      contentType,
    });

    return filename;
  } catch (error) {
    // Handle 401 errors specifically (poster not accessible/doesn't exist)
    if (error instanceof Error && error.message.includes('401')) {
      logger.debug(`Poster not accessible (401) for URL`, {
        url: originalName ? `${originalName} (${url})` : url,
        error: 'Poster not found or not accessible',
      });
      return null;
    }

    logger.error(`Failed to download poster from URL`, {
      url: originalName ? `${originalName} (${url})` : url,
      error: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}

/**
 * Clean up unused poster files (files that exist but are marked as inactive)
 */
export async function cleanupInactivePosterFiles(): Promise<number> {
  try {
    const registry = loadPosterHashRegistry();
    let deletedCount = 0;

    for (const [hash, entry] of Object.entries(registry)) {
      // Only clean up files that are marked as inactive and have filenames
      if (!entry.isActive && entry.filename && posterExists(entry.filename)) {
        await deletePosterFile(entry.filename);
        // Remove from registry after deleting file
        delete registry[hash];
        deletedCount++;
      }
    }

    if (deletedCount > 0) {
      savePosterHashRegistry(registry);
      logger.info(`Cleaned up ${deletedCount} inactive poster files`);
    }

    return deletedCount;
  } catch (error) {
    logger.error('Failed to cleanup inactive poster files:', error);
    return 0;
  }
}

/**
 * Export hash management functions for external use
 */
export { calculatePosterHash, findPosterByHash, loadPosterHashRegistry };

/**
 * Validate poster file buffer
 */
export function validatePosterBuffer(buffer: Buffer, mimeType: string): void {
  if (!ALLOWED_MIME_TYPES.includes(mimeType)) {
    throw new Error(
      `Invalid file type. Allowed types: ${ALLOWED_MIME_TYPES.join(', ')}`
    );
  }

  if (buffer.length > MAX_FILE_SIZE) {
    throw new Error(
      `File size too large. Maximum size: ${MAX_FILE_SIZE / (1024 * 1024)}MB`
    );
  }
}

/**
 * Generate and save a poster based on collection configuration
 * @param config Configuration for poster generation
 * @param originalName Optional original name for logging
 * @param collectionIdentifier Collection identifier to track generated posters (config.id or config.id-userId-mediaType)
 * @returns The saved filename
 */
export async function generatePoster(
  config: PosterGenerationConfig,
  originalName?: string,
  collectionIdentifier?: string
): Promise<string> {
  try {
    // Mark any existing auto-generated posters for this collection as inactive
    if (collectionIdentifier) {
      const existingPosters =
        findAutoGeneratedPostersByCollectionId(collectionIdentifier);
      if (existingPosters.length > 0) {
        markAutoGeneratedPostersAsInactive(existingPosters);
        logger.info(
          `Marked ${existingPosters.length} old auto-generated posters as inactive`,
          {
            collectionIdentifier,
            collectionName: config.collectionName,
          }
        );
      }
    }

    // Generate the poster buffer
    const posterBuffer = await generatePosterBuffer(config);

    // For auto-generated posters, we'll store temporarily to upload to Plex
    // Then we'll delete the local file and only keep the hash registry entry
    const posterHash = calculatePosterHash(posterBuffer);
    const tempFilename = `temp_generated_${posterHash.substring(0, 8)}.jpg`;
    const tempPath = path.join(POSTER_STORAGE_DIR, tempFilename);

    // Save temporarily for upload to Plex
    const processedBuffer = await sharp(posterBuffer)
      .resize(POSTER_WIDTH, POSTER_HEIGHT, {
        fit: 'cover',
        position: 'center',
      })
      .jpeg({ quality: 90 })
      .toBuffer();

    await fs.promises.writeFile(tempPath, processedBuffer);

    logger.info(
      `Generated temporary poster file for upload: ${tempFilename}${
        originalName ? ` (${originalName})` : ''
      }`,
      {
        collectionName: config.collectionName,
        collectionType: config.collectionType,
        size: processedBuffer.length,
        hash: posterHash.substring(0, 8),
      }
    );

    return tempFilename;
  } catch (error) {
    logger.error('Failed to generate poster:', error);
    throw new Error('Failed to generate poster');
  }
}

/**
 * Complete the auto-generated poster workflow after upload to Plex
 * Downloads the poster back from Plex to get the recompressed version,
 * stores only the hash registry entry (no file), and cleans up temporary file
 */
export async function completeAutoGeneratedPosterWorkflow(
  tempFilename: string,
  plexPosterUrl: string,
  collectionIdentifier: string,
  originalName?: string
): Promise<void> {
  try {
    // Download the poster back from Plex to get the recompressed version
    const axios = await import('axios');
    const response = await axios.default.get(plexPosterUrl, {
      responseType: 'arraybuffer',
      timeout: 30000,
      maxContentLength: MAX_FILE_SIZE,
      headers: {
        'User-Agent': 'Agregarr/1.0.0',
      },
    });

    const plexBuffer = Buffer.from(response.data);
    const plexHash = calculatePosterHash(plexBuffer);

    // Store hash-only entry for the Plex version
    addPosterToRegistry(plexHash, 'auto-generated-poster', {
      // No filename - we don't store the file for auto-generated posters
      originalName,
      collectionIdentifier,
      plexUrl: plexPosterUrl,
    });

    // Clean up temporary file
    const tempPath = path.join(POSTER_STORAGE_DIR, tempFilename);
    if (
      await fs.promises
        .access(tempPath)
        .then(() => true)
        .catch(() => false)
    ) {
      await fs.promises.unlink(tempPath);
      logger.info(`Cleaned up temporary poster file: ${tempFilename}`);
    }

    logger.info(
      `Completed auto-generated poster workflow - stored hash-only entry`,
      {
        originalName,
        collectionIdentifier,
        plexHash: plexHash.substring(0, 8),
        plexUrl: plexPosterUrl,
      }
    );
  } catch (error) {
    logger.error('Failed to complete auto-generated poster workflow:', error);
    // Don't throw - poster was already uploaded successfully
  }
}
